#include <cstdlib>
#include <string>

#include <gtest/gtest.h>

#include "a3_pingpong/pp_onnx_policy.hpp"

namespace {

nlohmann::json PlannerRevisionMetadata() {
  nlohmann::json profile = {
      {"policy_dt_s", 0.02},
      {"min_tts_s", 0.10},
      {"max_tts_s", 2.0},
      {"max_phase_rate_per_s", 4.0},
      {"max_phase_acceleration_per_s2", 20.0},
      {"max_deadline_revision_delta_s", 0.25},
      {"max_position_revision_delta_m", 0.10},
      {"max_velocity_revision_delta_mps", 0.50},
      {"max_normal_revision_delta_rad", 0.20},
      {"normal_unit_tolerance", 1e-4},
      {"early_deadline_tolerance_s", 1e-9},
      {"contract_version", "phase_governor_v1"},
      {"schema_version", 1},
  };
  // Generated by Python canonical_profile_bytes(sort_keys=True,
  // separators=(",", ":")); parser acceptance therefore detects any C++/Python
  // canonical-number or key-order drift instead of self-signing C++ bytes.
  const std::string digest =
      "3ebaca6b7f6ce1e841d5cf62aab3df38c796093ce563b6bfb4ef3048a0dd886a";
  return {
      {"enabled", true},
      {"revision_schema_version", 1},
      {"governor",
       {{"contract_version", "phase_governor_v1"},
        {"schema_version", 1},
        {"profile_sha256", digest},
        {"profile", std::move(profile)}}},
      {"initial_tts_range_s", {0.5, 1.8}},
  };
}

TEST(PpOnnxPolicy, PlannerTaskRevisionMetadataIsExactAndContentBound) {
  const auto parsed = a3_pingpong::ParsePpPlannerTaskRevisionModelContract(
      PlannerRevisionMetadata().dump());
  EXPECT_TRUE(parsed.trained);
  EXPECT_EQ(parsed.revision_schema_version, 1);
  EXPECT_EQ(parsed.governor.contract_version, "phase_governor_v1");
  EXPECT_DOUBLE_EQ(parsed.governor.policy_dt_s, 0.02);
  EXPECT_DOUBLE_EQ(parsed.initial_tts_lo_s, 0.5);
  EXPECT_DOUBLE_EQ(parsed.initial_tts_hi_s, 1.8);
  EXPECT_FALSE(a3_pingpong::ParsePpPlannerTaskRevisionModelContract("").trained);
}

TEST(PpOnnxPolicy, PlannerTaskRevisionMetadataFailsClosedOnDrift) {
  auto unknown = PlannerRevisionMetadata();
  unknown["unbound_default"] = 1;
  EXPECT_THROW(a3_pingpong::ParsePpPlannerTaskRevisionModelContract(unknown.dump()),
               std::runtime_error);

  auto partial = PlannerRevisionMetadata();
  partial.erase("initial_tts_range_s");
  EXPECT_THROW(a3_pingpong::ParsePpPlannerTaskRevisionModelContract(partial.dump()),
               std::runtime_error);

  auto changed = PlannerRevisionMetadata();
  changed["governor"]["profile"]["max_phase_rate_per_s"] = 4.1;
  EXPECT_THROW(a3_pingpong::ParsePpPlannerTaskRevisionModelContract(changed.dump()),
               std::runtime_error);

  auto disabled = PlannerRevisionMetadata();
  disabled["enabled"] = false;
  EXPECT_THROW(a3_pingpong::ParsePpPlannerTaskRevisionModelContract(disabled.dump()),
               std::runtime_error);
}

TEST(PpOnnxPolicy, LoadsOnlyPublishableRealModelWithStableInputTypeInfoLifetime) {
  const char* model_path = std::getenv("A3_PP_ONNX_PATH");
  if (model_path == nullptr || std::string(model_path).empty()) {
    GTEST_SKIP() << "set A3_PP_ONNX_PATH to a real exported policy.onnx";
  }

  a3_pingpong::PpOnnxPolicy policy(model_path);
  const int obs_dim = policy.obs_dim();
  EXPECT_TRUE(obs_dim == a3_pingpong::kObsDim || obs_dim == a3_pingpong::kObsDim179 ||
              obs_dim == a3_pingpong::kObsDim177 || obs_dim == a3_pingpong::kObsDim175 ||
              obs_dim == a3_pingpong::kObsDim110);
  EXPECT_EQ(policy.joint_names().size(), static_cast<std::size_t>(a3_pingpong::kNumJoints));
  EXPECT_EQ(policy.default_q().size(), a3_pingpong::kNumJoints);
  EXPECT_TRUE(policy.has_schema3_execution_contract());
  EXPECT_TRUE(policy.training_contract_exact());
  EXPECT_TRUE(policy.publishable_model_contract());
  if (obs_dim == a3_pingpong::kObsDim179) {
    EXPECT_FALSE(policy.face_normal_envelope().payload_sha256.empty());
    EXPECT_EQ(policy.face_normal_envelope().mount_normal_signs[0], 1.0);
    EXPECT_EQ(policy.face_normal_envelope().mount_normal_signs[1], -1.0);
  }
}

}  // namespace
